global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'intelliscalesim'

scrape_configs:
  - job_name: 'intelliscalesim-containers'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/monitoring/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s
